M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date Sab 12 Okt 2024 06:54:45 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-12T06:54:45+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.1969Y-2.1654
X1.122Y-1.1707
X2.0472Y-2.1654
M30
